variable "vpc_cidr" {}
variable "vpc_name" {}
variable "public_subnet_cidrs" {}
variable "azs" {}
variable "private_subnet_cidrs" {}
variable "igw_name" {}
variable "route_name" {}
variable "ami_id" {}
variable "server_type" {}
variable "keypair_name" {}
variable "server_name" {}